### ISSUE TITLE
HuggingFace space is down

### ISSUE THREAD

**Issue by mraaroncruz** [Wazzabeee/image-video-colorization#1]
There's some kind of Streamlit error on the huggingface space

https://huggingface.co/spaces/Wazzzabeee/image-video-colorization

![image](https://github.com/Wazzabeee/image-video-colorization/assets/175984/12265dca-1dbd-44dd-bbc3-e3da8f2992e0)

**Comment by Wazzabeee** [comment]
The Runtime Error is fixed now !

**Comment by mraaroncruz** [comment]
Nice. Thanks @Wazzabeee
